### ISSUE TITLE
pdf-cell vertical alignment

### ISSUE THREAD

**Issue by chrismurrph** [clj-pdf/clj-pdf#122]
This does not work:
`:valign :middle`
, what happens is that the text within the cell is still at the bottom
This is despite the fact I can get other attributes such as `:align :center` to work

**Comment by yogthos** [comment]
That looks like a bug, I might not have time to get look at it in the near future though. If you want to take a stab at it, I can help with doing a pr.

**Comment by chrismurrph** [comment]
I found a workaround, which might help the understanding of the bug. I explicitly set the height of pdf-cell, and then set the vertical alignment to be top:

    [:pdf-cell {:align :center 
                   :valign :top 
                   :style :bold
                   :size cc/bigger
                   :height 25} name]

**Comment by yogthos** [comment]
Thanks for investigating. It might be a limitation of the original itext code that you have to specify height explicitly in order to use valign. I guess for now I can update the readme to mention that.

**Comment by MawiraIke** [comment]
Hi again @yogthos, upon further investigation, I have realized that for vertical alignment to properly work in openpdf/itext, the ```.setUseAscender``` has to be set to true as mentioned in the docs [here](https://librepdf.github.io/OpenPDF/docs-1-1-0/com/lowagie/text/Cell.html#useAscender) and in [this SO fix](https://stackoverflow.com/a/42065318/10081740). If its okay with you, you can merge a fix for the same that i am attaching below.

**Comment by yogthos** [comment]
Thanks for investigating and doing the PR, I just pushed out 2.5.0 with the fix.

**Comment by MawiraIke** [comment]
Awesome!
