### ISSUE TITLE
Using a :phrase in :pdf-cell drops :align option

### ISSUE THREAD

**Issue by jwr** [clj-pdf/clj-pdf#153]
The `:align` option in `:pdf-cell` seems to stop working if a `:phrase` is used inside (to specify styles, such as bold text).

```
(pdf/pdf
 [{:encoding :unicode}
  [:pdf-table
   {:width-percent 100}
   [33 33 33]
   [[:pdf-cell {:align "right"} 
     "This is aligned right"]
    [:pdf-cell {:align "right"} 
     [:paragraph {} "This is aligned right, too"]]
    [:pdf-cell {:align "right"}
     [:phrase {} "This is not, which is a bug"]]]]]
 "/tmp/doc.pdf")
```

**Comment by yogthos** [comment]
Might be an artifact of how paragraphs vs phrases work in itext. I'll try take a look if I get a chance.

**Comment by MawiraIke** [comment]
Seems like phrases don't obey ```align``` in itext. To fix the issue I'd suggest adding a ```phrase``` to a ```paragraph``` easily as, 
```clojure
(Paragraph. phrase)
```
I'd be glad to submit a PR if this is okay with you @yogthos .

**Comment by yogthos** [comment]
@MawiraIke a PR would be most welcome :)
