### ISSUE TITLE
Extensibility

### ISSUE THREAD

**Issue by piranha** [clj-pdf/clj-pdf#154]
I want to draw barcode on a pdf, which led me to [this](http://itextsupport.com/apidocs/itext5/latest/com/itextpdf/text/pdf/Barcode.html#placeBarcode-com.itextpdf.text.pdf.PdfContentByte-com.itextpdf.text.BaseColor-com.itextpdf.text.BaseColor-) API. There is no way I can get access to `PdfWriter` to create `PdfContentByte`, because whole API is just data structure.

I had an idea: if `condp` inside of `make-section` is changed to a multi-method, so that new types of elements can be added, plus `PdfWriter` is bound to a dynamic variable - that way clj-pdf would allow extending itself without making changes to code.

Maybe I'm going wrong direction, then I'd really love someone to correct me. :)

**Comment by yogthos** [comment]
I think that's a great idea, would you be up for doing a pr to add that?

**Comment by piranha** [comment]
It seems I'll need that shortly, so yeah. :-)

**Comment by piranha** [comment]
#155
