### ISSUE TITLE
If a class has no corresponding stylesheet entry, it throws an NPE without any information

### ISSUE THREAD

**Issue by Kah0ona** [clj-pdf/clj-pdf#159]
if you have [:paragraph.foo "bla"] but there is no stylesheet entry for :foo, the system will throw a nullpointerexception without error message, that is hard to read.

As an aside, I think there are some more cases where wrong input just fails silently, or gives an error that is quite obscure.

Can we do something to improve this? Ie. better error messages OR allow a bit more things, ie. if there's a nil in the datastructure just ignore it.

**Comment by yogthos** [comment]
That sounds reasonable to me. I wouldn't have time to look at this in the near future, but I could help with a PR if you'd be interested in putting one together.

**Comment by Kah0ona** [comment]
Yeah, I'll try to make some time for this, soon.

**Comment by martinklepsch** [comment]
Also just ran into this. @Kah0ona do you still want to take a stab at this?

**Comment by Kah0ona** [comment]
Hm realistically I'd say I don't have a lot of time right now, and leaving on holiday soon.

So if you feel like fixing it, please go ahead.
