### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by Jarzka** [clj-pdf/clj-pdf#162]
Hello

Where is the changelog of different version updates? I would like to know what has changed between minor/patch releases.

**Comment by yogthos** [comment]
Hi,

I haven't been keeping a change log for the project, perhaps it might be worth starting one. Currently, the only thing to do would be to go through the commit log. In general, I haven't been making breaking changes to the exiting API, so new versions tend to either be bug fixes or new features.

**Comment by yogthos** [comment]
I've added a changelog [here](https://github.com/clj-pdf/clj-pdf/blob/master/CHANGELOG.md), and will keep it updated going forward.
