### ISSUE TITLE
How to select the pdf download settings (Without just create a pdf in the folder, showing a download box) 

### ISSUE THREAD

**Issue by gabrielmonteles** [clj-pdf/clj-pdf#164]
![image](https://user-images.githubusercontent.com/12904035/52419065-1b3b2000-2ace-11e9-8d49-d0a3ecaca39f.png)

I wanna click in the "pdf download button" and I would like this box to open. How can I do it?

**Comment by gabrielmonteles** [comment]
I think what I have to do is generate a pdf in the browser, then, the box will appear. Not to create a pdf in the folder. But I dont know how to generate like this.

**Comment by yogthos** [comment]
The library needs the JVM to run, so you can't use it to generate content in the browser. You could serve the PDF from a server by specifying the correct content type as I mentioned earlier. In any case, this is outside of the scope of the functionality for the library so I'm going to close the issue.
