### ISSUE TITLE
Bump to OpenPDF 1.3.0

### ISSUE THREAD

**Issue by vincent-dm** [clj-pdf/clj-pdf#176]
OpenPDF release a significant update: https://github.com/LibrePDF/OpenPDF/releases/tag/1.3.0

Can you upgrade this library to use it?

**Comment by yogthos** [comment]
Hi, I think updating to the latest version would be good. I did a quick test and there are some breaking API changes. I'll try find some time to take a look, but I'd also be open to a PR.

**Comment by yogthos** [comment]
Finally, got around to updating the dependency, everything appears to be working with OpenPDF 1.3.1

https://github.com/clj-pdf/clj-pdf/pull/177
