### ISSUE TITLE
Custom chunk fonts stopped working in 2.3.8

### ISSUE THREAD

**Issue by michihuber** [clj-pdf/clj-pdf#178]
Upgrading from 2.3.6 to 2.3.8 broke the following setup:

I had a custom font set in :ttf-name set in the document config map, and on occasion a custom :ttf-name set in a chunk. The document ttf-name kept working, but the chunk "overrides" were ignored in 2.3.8.

**Comment by yogthos** [comment]
Thanks for the heads up. Just pushed out 2.3.9 with a fix. Let me know if everything looks good on your end.

**Comment by michihuber** [comment]
Wow, that was fast.

Works again, thank you very much for the quick fix!
