### ISSUE TITLE
Add checkboxes into PDF

### ISSUE THREAD

**Issue by WorldsEndless** [clj-pdf/clj-pdf#179]
I'm reproducing a form in which I need to display checked or unchecked boxes (note: I do NOT need them to be interactive; just to correctly display check or uncheck for the data I've received). How can I insert visible checkboxes?

**Comment by yogthos** [comment]
The easiest way would be to use a TTF font that supports unicode characters. [Here's](https://www.fileformat.info/info/unicode/char/2611/fontsupport.htm) a list of fonts with support for the ☑ character. So, as an example if you grab dejavu-sans [here](https://fonts2u.com/dejavu-sans.font), then you could do the following:

```clojure
(pdf
  [{:font {:encoding :unicode :ttf-name "DejaVuSans.ttf"}}
   [:list {:symbol "☑"} "foo" "bar" "baz"]]
  "foo.pdf")
```

**Comment by WorldsEndless** [comment]
This looks good. At production time, will it work independent of host system if the ttf is included on the class path in the jar?

**Comment by yogthos** [comment]
Yup, as long as you package the font in the jar it should work fine.
