### ISSUE TITLE
allow images in headers

### ISSUE THREAD

**Issue by yogthos** [clj-pdf/clj-pdf#181]
Currently, images are not supported in headers due to limitations in OpenPDF API. However, a base64 encoded image can be used in a header. This enhancement is for allowing images in headers by automatically converting them to base64 within the library.

**Comment by MawiraIke** [comment]
Hey, awesome library, I am enjoying using it a lot, and would be glad to make my contributions. 
Seems like images can be added to headers while in ```:table``` > ```:pdf-table``` > ```paragraph``` e.g as 
```Clojure
(pdf
  [{:header {:table
             [:pdf-table
              {:border false}
              nil
              [[:paragraph [:chunk [:image "test/mandelbrot.jpg"]]]]]}}
   [:list {:roman true}
    [:chunk {:style :bold} "a bold item"]
    "another item"
    "yet another item"]
   [:phrase "some text"]
   [:phrase "some more text"]
   [:paragraph "yet more text"]]
  "ike-doc.pdf")
```
Did you intend to add images to headers directly? If this is the case I would be glad to give it a stab  it if that's okay with you. I have tried to add my Base64 Image String as the header but I get a StackOverflow error and will possibly consider other ways of merging the image with the OpenPDF API.

Best,
Ike.

**Comment by yogthos** [comment]
Hi, 

Imagines in headers seems like a handy thing to me, and a PR for this would be very welcome. :)

**Comment by MawiraIke** [comment]
I have fixed this in [this PR](https://github.com/clj-pdf/clj-pdf/pull/190). However, my fix is only for ```:header``` tag and not for ```letterhead```. Did you intend this to have the same effect? I can see that the letterhead is rendered at a different place, when the document is open and before the header is added.

**Comment by MawiraIke** [comment]
If this is what was planned,  I would be glad to add a commit that adds that functionality.

**Comment by yogthos** [comment]
Thanks for the PR, just pushed out a 2.4.5 to Clojars with the update.
