### ISSUE TITLE
Adding sufficient spacing after header

### ISSUE THREAD

**Issue by WorldsEndless** [clj-pdf/clj-pdf#182]
Because of the size of my header table, I have to start each page with `[:spacing 3.5]`. This isn't possible when content may dynamically produce multiple pages, though, since spacing within the header has no effect upon "float"-like behaviors of the title. Seems like an inverse of #114 ; I want my headers to ignore my margins. 

Practically speaking, I solved this with trial-and-error with the following settings, but this is far from ideal:

``` clojure
;; meta map
{:top-margin 90
 :header {:y 800 ;; this essentially produces a negative margin for the header
          :table (header-table)}}
```

**Comment by MawiraIke** [comment]
Hi @yogthos I have tried out some fix for this and its working. 
Attaching it below.

**Comment by yogthos** [comment]
Fantastic thanks, just pushed out 2.5.1 with the fix. 👍
