### ISSUE TITLE
Is there any way to position text with x and y?

### ISSUE THREAD

**Issue by shkabatur** [clj-pdf/clj-pdf#183]
Sorry for the issue. But i'm new to clojure and my task needs the ability to specify x and y when i draw the text. But i cant find how do this.

**Comment by WorldsEndless** [comment]
I'm not sure if this will help, but I don't know of a "position: absolute" equivalent here. But I tweak the position of my elements with `:padding` attributes. Example:

``` clojure
[[:pdf-table {:spacing-before 3 :border true} nil
                  [[:pdf-cell {:valign :middle
                               :padding-top 0
                               :padding-bottom 5} description]]]]
```

**Comment by yogthos** [comment]
Using a table is probably the easiest option at the moment.

**Comment by shkabatur** [comment]
Thanks, I'll try.
