### ISSUE TITLE
Exposing setUnderline

### ISSUE THREAD

**Issue by michihuber** [clj-pdf/clj-pdf#184]
I'd like to contribute a patch that exposes [setUnderline](https://github.com/LibrePDF/OpenPDF/blob/61004ce592c5b754309adf997abe4f2d0ace0e56/openpdf/src/main/java/com/lowagie/text/Chunk.java#L526), to give more control over the underline style. Would you accept such a patch? Any suggestions for a possible API and where this could be added?

**Comment by michihuber** [comment]
I'm thinking add this here: https://github.com/clj-pdf/clj-pdf/blob/master/src/clj/clj_pdf/section/core.clj#L62

:chunk could accept a seq of `:underlines [{:y-position <number> :thickness <number>}]`

**Comment by yogthos** [comment]
Hi, yeah that sounds reasonable and a patch would be great.

**Comment by michihuber** [comment]
Thank you for the quick merge!

Your test setup is great, clone to PR took a few minutes.

**Comment by yogthos** [comment]
👍
