### ISSUE TITLE
2.5.1 breaks top-margin

### ISSUE THREAD

**Issue by markusalbertgraf** [clj-pdf/clj-pdf#200]
Hi,
when I update to 2.5.1, non-header text ignores top-margin and clobbers the header.
If no header is defined, top-margin behaves as expected but with header text moves up to clobber it.
I am on OpenJDK 1.8.0_252-b09.
Rollback to 2.5.0 fixes the issue.

Sidenote:
In the examples header uses :y = 50.  This puts the header near the bottom of the page.
I need to use :y = 810 on A4 paper to put it at the top.

**Comment by yogthos** [comment]
Looks like the regression is caused by [the fix](https://github.com/clj-pdf/clj-pdf/pull/198) to spacing after header, @MawiraIke could you take a look.

**Comment by MawiraIke** [comment]
Sure, on it ASAP.

**Comment by MawiraIke** [comment]
Made a fix for this @yogthos . Tagging it below.

**Comment by yogthos** [comment]
@markusalbertgraf just pushed out 2.5.2 with the fix

**Comment by markusalbertgraf** [comment]
@yogthos Thank you, but sadly it does not fix the bug.

**Comment by markusalbertgraf** [comment]
My header follows this template from the readme.  Am I missing something?
```
{:header {:x 20
          :y 50
          :table
          [:pdf-table
           {:border false}
           [20 15 60]
           ["this is a table header" "second column" "third column"]]}
 :footer {:table
          [:pdf-table
           {:border false}
           [20 15 60]
           ["this is a table footer" "second column" "third column"]]}
```

**Comment by yogthos** [comment]
Yeah, that should work since it's just the default case, @MawiraIke looks like we're not quite there yet. :)

**Comment by MawiraIke** [comment]
This must be due to the ```:footer``` i think. I didn't expect it to be affected but seems like it is. Making a fix immediately.

**Comment by yogthos** [comment]
👍

**Comment by MawiraIke** [comment]
Fair to note that the footer is not the problem as initially thought. The code works if the body is, ```:paragraph```, or ```:list``` but causes the bug on ```:phrase``` and ```:table```. Digging deeper to see whats up. 

![With list](https://user-images.githubusercontent.com/38689046/85945108-2ea98e00-b944-11ea-8190-09f480172901.png)

![With paragraph](https://user-images.githubusercontent.com/38689046/85945118-39fcb980-b944-11ea-85b9-e2f74e4d7a79.png)

![With phrase](https://user-images.githubusercontent.com/38689046/85945124-41bc5e00-b944-11ea-9f47-aec3a3f06846.png)

**Comment by yogthos** [comment]
Oh interesting, looks like there might be inconsistency in how librePDF handles rendering. Thanks for digging into it.

**Comment by MawiraIke** [comment]
Yes. I am trying to see if its something i can fix, even with a hack. But in case i fail, i will push some fix i had left for adding footer height margins when adding the header margins and cleanup regarding the same.

**Comment by yogthos** [comment]
Sounds like a plan, there were a few things I ended up having to hack around before. The API can be surprising at times.

**Comment by yogthos** [comment]
@markusalbertgraf pushed out 2.5.3, hopefully everything's working as expected this time around :)

**Comment by MawiraIke** [comment]
I think the only reason that this issue is happening must be in librePDF. I can't find another reason where. About a hack, i think that the only sure way of knowing that the first element is a phrase in the body is quite untidy and would result in extra complexity as ```.setMargins``` has to be called for each page but if the first element is a phrase
For page one, the easiest way i can think of is [here](https://github.com/clj-pdf/clj-pdf/blob/master/src/clj/clj_pdf/core.clj#L519) where this condition can be perfomed,
```Clojure
(= (ffirst content) :phrase))
```
But that would consequentially mean that the result be passed to ```:setup-doc``` to set margin before the document is opened. And then maybe have to set the margin in the following page back to normal if the first element is not a ```:phrase``` and recurring...

**Comment by MawiraIke** [comment]
> @markusalbertgraf pushed out 2.5.3, hopefully everything's working as expected this time around :)

Phrases should still overlap headers since i couldn't think of a neater way of doing a hack but everything else should be fine, e.g ```:paragraph``` for phrase.

**Comment by yogthos** [comment]
I think that's a reasonable compromise.

**Comment by markusalbertgraf** [comment]
@yogthos @MawiraIke Thank you for your work!
The bug seems to be squashed.
