### ISSUE TITLE
Table being truncated after first page

### ISSUE THREAD

**Issue by pmonks** [clj-pdf/clj-pdf#203]
My understanding (which may be wrong) is that a `[table]` that's too big to fit on one page will be automatically split across pages, however I'm not seeing that behaviour.  Instead, after the first page the table contents are truncated, and don't appear in the PDF file at all.

### Steps to Reproduce:

Download [`large-table-edn.zip`](https://github.com/clj-pdf/clj-pdf/files/4873372/large-table-edn.zip), unzip it to produce `large-table.edn`, then:

```
$ clj -Sdeps '{:deps {clj-pdf #:mvn {:version "2.5.3"}}}'
Clojure 1.10.1
user=> (require '[clojure.java.io :as io])
nil
user=> (require '[clojure.edn :as edn])
nil
user=> (require '[clj-pdf.core :as pdf])
nil
user=> (def pdf-data (edn/read (java.io.PushbackReader. (io/reader "large-table.edn"))))
#'user/pdf-data
user=> (pdf/pdf pdf-data "large-table.pdf")
nil
```

Open `large-table.pdf` and compare to the source data - you should see that the last visible row in the table is the row with the text "Scheduled start 8:15 PM UTC:"; the following 14 rows contained in the source data are missing.

**Comment by yogthos** [comment]
Looks like it's caused specifically by setting the background color in the header, and removing `{:background-color [200 200 200]}` renders all the items as expected. I bumped up to the latest version of openpdf, and that appears to fix the problem on my end. I just pushed out `2.5.4`, let me know if that fixes the problem for you.

**Comment by pmonks** [comment]
Awesome!  Will take it for a spin tonight.

It didn’t even occur to me to mess with the background colour of the table heading row- that’s bizarre.  😉

**Comment by yogthos** [comment]
Yeah, that certainly was unexpected. :)

**Comment by pmonks** [comment]
Looking great in my tests here - thanks for hunting this down!
