### ISSUE TITLE
Idiomatic or non-hacky way to begin list numbering at an arbitrary value?

### ISSUE THREAD

**Issue by kees-** [clj-pdf/clj-pdf#214]
Hey there... Consider some example code from what I'm working on.

```clojure
(into [:pdf-table.body.block-spacer
        [36 64]]
      (map recipe-section sectioned-elements])))

;; ...

(defn recipe-section [block]
  ;; ... other elements
  [[:pdf-cell.section.procedures
     [:list
       (for [recipe-step (block :procedures)]
         [:phrase.procedure-item recipe-step])]]])
```

`(block :procedures)` refers to a vector containing an arbitrary number of strings, for each iteration of the list comprehension.

So the intended result from this snippet is a table of spaced lists of string phrases.

When the list metadata is set to numbered, each restarts from `1.` as it should.

---

#### The rendered equivalent of what I'm looking at now.
<img width="530" alt="210920-10 33 17 AM" src="https://user-images.githubusercontent.com/6820950/134048221-2aa03916-853e-47b7-bc74-d06a9f1f5e72.png">

#### And my end goal.
![Pistachio-Gelato](https://user-images.githubusercontent.com/6820950/134048304-f7cff658-36c0-4498-9c12-031a71a60153.jpg)

---

I expect to make the lists unnumbered, change the phrases to tables, and add cells with custom-numbered content as prefixes. Alternatively, keeping each block of string-vectors in a single list and figuring out how to separate them into corresponding sections seems like a mild headache for someone as new to clojure as I am.

Just wondering, however, if there is a reasonable method to achieve continuity with either `clj-pdf` itself or its underlying libraries. Or, if there is just a direction anyone can point me in to keep experimenting myself. Thanks!!!

Otherwise `clj-pdf` is excellent and the level of concision for expressing dynamic and styled content constantly surprises me.

**Comment by yogthos** [comment]
Unfortunately, there isn't a way to start numbering from an arbitrary value at the moment. So, that kind of a hack would probably be the best option. There might be a way to achieve that with the underlying OpenPDF library, if you have a chance to look I'd be happy to help with a PR for the feature. And glad to hear the library has been working out well so overall. :)

**Comment by kees-** [comment]
Thanks for replying!
It was a pretty trivial workaround once I had a moment.

I'd love to try looking at the libraries when I get time down the road. If so, happy to bring it up again. Otherwise closing the issue for now.

**Comment by yogthos** [comment]
Sounds good, and feel free to open a new issue or a PR if you get a chance. :)
