### ISSUE TITLE
Can you access the current page number?

### ISSUE THREAD

**Issue by insano10** [clj-pdf/clj-pdf#216]
I need to render the page number inside the page itself, rather than just in the footer. Is it possible to refer to this field while defining the elements? Thanks.

**Comment by insano10** [comment]
If it's not built into the libraryPoking around I see this could be implemented by:

- adding a custom 'on-page-start' event handler
- accessing the page number through the `getCurrentPageNumber` function on the `com.lowagie.text.pdf.PdfWriter` that gets passed into the event handler

Does that sound plausible?

**Comment by yogthos** [comment]
Yeah, there is a [setPageEvent](https://github.com/clj-pdf/clj-pdf/blob/18f41ec9c2152085030ce3cfe31ea9afefd27ada/src/clj/clj_pdf/core.clj#L396) method in openpdf that could be used to manipulate the page. It's not exposed via clj-pdf API at the moment, but it would be a reasonable feature to add. One option would be to add `:page-event` key to the configuration map that would expose the underlying setPageEvent API and allow the user to use opendpf API directly on the page. I probably won't have time to look in the near future, but I could help guide a PR if you'd be up for giving it a shot. :)

**Comment by insano10** [comment]
I actually ended up needing the total number of pages as well as the current page number so ended up using a stamper to achieve what I wanted

**Comment by yogthos** [comment]
Ah yeah that's always a good option. :)
