### ISSUE TITLE
Letterhead positioning broken

### ISSUE THREAD

**Issue by insano10** [clj-pdf/clj-pdf#217]
The merging of issue #161 has broken the positioning of letterheads on the PDFs. Previously the handling of the top margin on each page was modified by [this function](https://github.com/clj-pdf/clj-pdf/blob/master/src/clj/clj_pdf/core.clj#L171), which allowed for a different top margin of a page with a letterhead vs one with a header.

The `OnBeforeStartPage` function is not present on the OpenPdf version of `PdfPageEventHelper` so this function never fires and doesn't compensate for letterheads.

The current observed behaviour for a PDF with a letterhead and header is that the first page has a top margin that allows for a header (but doesn't render it) then renders the letterhead underneath, leaving a header-sized blank space at the top of the page.

Is there an equivalent place to hook in to modify the margins as before? I tried changing the function to `OnStartPage` but that was too late to apply the change.

**Comment by yogthos** [comment]
Perhaps a workaround could be to check the page number in the PdfPageEveentHelper if it's accessible, and then implement letterhead behavior that way?

**Comment by insano10** [comment]
I see in the old version of `PdfDocument` this comment:
```
// the whole point of the onBeforeStartPage event is to make it so that it's possible to react
        // to each new page at a point where it's still possible to change the page size and margins
        // (among other settings) and have it take effect for the very next page that is being started.
        // onStartPage and onEndPage are too late for this (though onEndPage would be the next best spot
        // for this kind of code).
        // however, in order to not break compatibility with existing code, i've opted to not move when
        // onOpenDocument is triggered. as a result it's a little bit weird in that onBeforeStartPage
        // will be triggered before onOpenDocument.
        // (i personally do feel that onOpenDocument is being triggered too late... but whatever)
        // - Gered King, March 2017
        if (pageEvent != null) {
            pageEvent.onBeforeStartPage(writer, this);
        }
```
I will try adding something in `onEndPage` as suggested.

**Comment by yogthos** [comment]
Sounds like a plan, seems like it should work for this particular use case since we don't need to change page size or the margins.

**Comment by insano10** [comment]
issue now fixed
