### ISSUE TITLE
PDF/A Standard Conformity

### ISSUE THREAD

**Issue by arational** [clj-pdf/clj-pdf#226]
It is possible to use openpdf in a way that the generated PDF conforms to most of the PDF/A standards. I made some local adjustments of clj-pdf to meet PDFA/3a conformity of a certain set of elements. I could provide a pull request for that. This could be used as a starting point to introduce this feature.

Is there an interest for PDF/A Standard Conformity in general?

**Comment by WorldsEndless** [comment]
Long time user and watcher of PDF-Tools here. I had never heard of PDF/A standard; I found it explained a bit here https://en.wikipedia.org/wiki/PDF/A .

In general I am a big fan of supporting open standards. But what changes would PDF/A conformance require of the reader? From what I can tell, it would do more to reduce general support of PDFs than to increase it.

Again, I'm new to this conversation and topic. But what actual changes would be needed?

**Comment by arational** [comment]
There are several properties described by the specification which have to be met by the PDF. There are several versions of the PDF/A standard which have slightly different goals. In our case PDFA/3a. Here is a [brief description](https://www.pdf-tools.com/en/resources/pdfa-archive-format/pdfa-3-overview/). Here are some examples of some changes which would be necessary for PDFA/3a:

- Tagging enabled.
- Set the default blending colorspace. For instance [set it to RGB](https://javadoc.io/doc/com.github.librepdf/openpdf/latest/com/lowagie/text/pdf/PdfWriter.html#setRgbTransparencyBlending(boolean))
- Embed fonts with all glyphs.
- Provide XMP Metadata Stream
- [Set default colorspace data](https://javadoc.io/doc/com.github.librepdf/openpdf/latest/com/lowagie/text/pdf/PdfWriter.html#setDefaultColorspace(com.lowagie.text.pdf.PdfName,com.lowagie.text.pdf.PdfObject))

If there is interest in general, I can show the exact changes by posting a pull request.
I use [veraPDF](https://github.com/veraPDF/veraPDF-validation) to validate the PDF data stream, which will give an exact report of what has to be changed in the PDF to conform to the desired PDFA standard.

**Comment by yogthos** [comment]
That sounds like it would be a useful update, I'm definitely open to a PR for the functionality.

**Comment by arational** [comment]
Sorry for the long delay. I pushed the PR now [here](https://github.com/clj-pdf/clj-pdf/pull/237).
