### ISSUE TITLE
How to use nested loops 

### ISSUE THREAD

**Issue by javid90khan** [clj-pdf/clj-pdf#227]
I have a nested data structure that I am trying to use to create a pdf:
`Parent -> Children -> GrandChildren`

```
(for [child [Children]]
  [:paragraph]
  [:paragraph]
  [:pdf-table
  (for [grandChild [GrandChildren]]
      [:pdf-cell]
  )
)
```

Now the problem is that the parent `for` loop only accepts one item. If I nest everything in a paragraph, it won't accept a nested loop. 

__PS:__ I have almost no experience with Clojure and new to this library.

**Comment by markusalbertgraf** [comment]
I normally use (into [:parent] coll-of-children) for this.

**Comment by markusalbertgraf** [comment]
`[:pdf-table {:border false} [40 20 40] [[:pdf-cell "hallo"][:pdf-cell "hello too"]]]` is what you want to end up with.

**Comment by yogthos** [comment]
If your children are each a collection of item you'd like to put in individual tables then you'd do something like the following:

```clojure
(let [children
      [["foo" "bar" "baz"]
       ["hallo" "hello too" "and me"]]]
  (for [child children]
   [:pdf-table 
    {:border false}
    [40 20 40]
    (for [grand-child child]
      [:pdf-cell grand-child])]))
```

**Comment by javid90khan** [comment]
Thanks you so much for the prompt response. I have some direction now.

@yogthos I tried to use the example above but I want to be able to spit out rows inside the second `for loop` instead of cells.

Something like this:
```
   (let [children
         [["foo" "bar" "baz"]
          ["hallo" "hello too" "and me"]]]
     (for [child children]
       [:pdf-table
        {:border false}
        [40 20 40]
        (for [grand-child child]
          [[:pdf-cell grand-child]])]))
```

This errors: 
```
 java.lang.ClassCastException: clojure.lang.PersistentVector cannot be cast to clojure.lang.Named
```

I am able to achieve it using [:table] by doing a (into). Can you please advise if I can do the above using [pdf-table] as I find it easier to work with.

**Comment by yogthos** [comment]
oh sorry had a typo in the example, there's an extra set of brackets around `:pdf-cell`, here's a full example:

```clojure
(pdf
 [{}

  (let [children
        [["foo" "bar" "baz"]
         ["hallo" "hello too" "and me"]]]
    (for [child children]
      [:pdf-table
       {:border false}
       [40 20 40]
       (for [grand-child child]
         [:pdf-cell grand-child])]))]
 "table.pdf")
```

**Comment by yogthos** [comment]
ah, so it sounds like this might be what you're looking for:

```clojure
(let [children [{:foo "foo" :bar "bar" :baz "baz"}
                {:foo "foo" :bar "bar" :baz "baz"}]] 
  (pdf/pdf
   [{}
    (into
     [:table {}]
     (for [{:keys [foo bar baz]} children]
       [[:cell foo] [:cell bar] [:cell baz]]))]
   "doc.pdf"))
```

**Comment by javid90khan** [comment]
Thanks. But can I do the same using `[:pdf-table]`?

**Comment by yogthos** [comment]
Yup, it's just a matter of generating a data structure that matches the API:

```clojure
(let [children [{:foo "foo" :bar "bar" :baz "baz"}
                {:foo "foo" :bar "bar" :baz "baz"}]]
  (pdf/pdf
   [{}
    (into
     [:pdf-table [10 20 15]]
     (for [{:keys [foo bar baz]} children]
       [[:pdf-cell foo] [:pdf-cell bar] [:pdf-cell baz]]))]
   "doc.pdf"))
```

**Comment by javid90khan** [comment]
Thanks a lot. That worked like a charm. Really appreciate the prompt response and patience.
