### ISSUE TITLE
Table with :widths is incompatible with colspan

### ISSUE THREAD

**Issue by Sardtok** [clj-pdf/clj-pdf#242]
When using widths and colspan, a cell spanning multiple columns is counted as a single column. It is rendered spanning the requested number of columns, but because it is counted wrong, empty cells have to be inserted to avoid an exception. Any following row, is then pushed in by that number of columns.

```clojure
(pdf/pdf
  [{:title "Colspan bug"}
   [:table {:widths [2 4]}
    [[:cell "Hey"] [:cell "I'm on the right!"]]
    [[:cell {:colspan 2} "I'm all over"] nil]
    [[:cell "Hey"] [:cell "I should be on the right, but I'm not!"]]]]
  "doc.pdf")
```

**Comment by Sardtok** [comment]
I had a quick look at the code, and the above example might not be a specific enough test case to break the count against widths.

However, I found a workaround by specifying :num-cols on the table the count is ignored and colspan works as intended.

**Comment by Sardtok** [comment]
We have these tables within a cell of another table, and the number of rows and whether rows have colspan or not is dependent on the data passed into the renderer. So the problem is actually for tables with a single row with a single colspan cell:

```clojure
(pdf/pdf
  [{:title "Colspan bug"}
   [:table {:widths [2 4]}
    [[:cell {:colspan 2} "I'm all over"]]]]
  "doc.pdf")
```
Fails, although the number of spanned columns is correct. So instead of `(map count rows)`, it should calculate the number of columns based on the spans, where cells without a defined colspan is considered 1. So something like this:

```clojure
(defn- spanned-columns [cell]
  (if (and (sequential? cell) (associative? (second cell)))
    (get cell :colspan 1)
    1))

...

   cols        (or num-cols (apply max (cons header-cols (reduce + (map spanned-columns rows)))))
```

I have not tested this suggestion, though, I just quickly threw it together in the comment field.

**Comment by yogthos** [comment]
That looks like it might work. Any chance you'd be up to put together a PR for this? :)
