### ISSUE TITLE
Can't get :header to work with :paragraph formatting

### ISSUE THREAD

**Issue by PunkWare** [clj-pdf/clj-pdf#27]
Hi,

According to the doc, headers can be formatted via a vector of paragraphs, but I can't get it to work.
Here's what I do:
(pdf [{} [:table {:header [{:color [100 100 100]} [:paragraph {:align :center} "FOO"]] :CellSpacing 20} ["foo"]]] "doc.pdf")

=>UnsupportedOperationException nth not supported on this type: Keyword  clojure.lang.RT.nthFrom (RT.java:857)

**Comment by inturi99** [comment]
how to add image tag in  table header

**Comment by inturi99** [comment]
I am writing this bellow code:
  
[:table {:header [:paragraph [:heading  [:image {"align" :center
                                                       :min-height 5
                                                       }  "resources/public/dist/img/itinerary.jpg"]]]
               :widths [1 1 1 3]
               :style :bold :size 11  :family :arial
               :min-height 20
               :align :center
               :background-color [235 235 231]
               }
           ["       Voucher"  "           Date " "         Time"       "                             Description" ]
       ]
     ["123"   "2014-01-01"  "12.00PM" "NO"]
      )  
     ]


Not working 

java.lang.UnsupportedOperationException: nth not supported on this type: Keyword
	at clojure.lang.RT.nthFrom(RT.java:947)

**Comment by yogthos** [comment]
The `:header` has to contain a vector of header columns:

```clojure
[:table
     {:header
      ["heading 1"
       "heading 2"
       "heading 3"
       [:image
        {:align :center :min-height 5}
         "resources/public/dist/img/itinerary.jpg"]]
      :min-height 20
      :align :center
      :background-color [235 235 231]}     
     [" Voucher" " Date " " Time" " Description"]
     ["123" "2014-01-01" "12.00PM" "NO"]]
```
Unfortunately, the `:widths` key isn't compatible with images, and will leave them blank.

**Comment by inturi99** [comment]
its working, thank you yogthos.
